os: osx
osx_image: xcode12.5
language: swift
script: xcodebuild clean build test -workspace iTunes-Demo.xcworkspace -scheme "CI" -sdk iphonesimulator14.5 -destination "platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
