name: CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
    - name: Build and Test
      run: xcodebuild clean build test -workspace iTunes-Demo.xcworkspace -scheme "CI" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO 

